### ISSUE TITLE
Stopped at latest block number

### ISSUE THREAD

**Issue by UdinChan** [soos3d/Retrive-and-display-pending-transactions-Web3.py#1]
I'm running this locally on my local node, after displaying latest block code exiting and not returning any hash.
Whats wrong?

**Comment by soos3d** [comment]
Does it give you any error? if it doesn't, it might be that there are no pending transactions in that moment, it happened a few times while testing it. You can put it in a while loop to make it run continuously and pick up pending transactions when they show up. 

You can also check out my Skillshare class WEB3.py: Interact with the Blockchain
Get 30 days for free using this link! https://skl.sh/3McEymV

It can be that the node you are accessing does not support the pending transaction filter, for example the free infura ETH node does not support that.
if you use a node from chainstack it works for sure! https://chainstack.com/
